### ISSUE TITLE
updates in ccf_wrap.tbl

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-utils#12]
I thought I had understood that updating (=adding lines to) ccf_wrap.tbl in the github branch was enough that the ccf_wrap python code would find the requests and execute them, by checking every 30min. Isn't that so? I added a few lines and it doesn't seem to go through. What am I missing? thanks!

**Comment by njcuk9999** [comment]
So unfortunately that won't automatically put the changes in the master - only your branch.
You have to wait for one of us to accept the changes into the master.

If this file needs updating regularly and the results of the updated table are needed instantly we need to think of another way to do it.

There are a few options:
1. we have a branch that is "unlocked" that you and others can edit `ccf_wrap.tbl` instantly and save the changes to that branch (like you do now but to a branch that is more permanently around) then Etienne will have to change the link to the `ccf_wrap.tbl` to look in this branch instead of the master
2. we host that file somewhere else @CharlesCadieux has some experience (or at least is learning) how to interface python with google sheets - so it could be we have the `ccf_wrap.tbl` as a google sheet and have a function that accesses that - then you would just edit the google sheets document and the code would go to that (should be instantaneous).

I'd like to here @CharlesCadieux and @eartigau option on these options !

**Comment by CharlesCadieux** [comment]
Hi Claire and Neil,

I think Étienne ended the `ccf_wrap.py` loop. `ccf_wrap.py` is looking in the cfht_july1 folder, which contains data reduced with the 0.6.129 DRS. He was working with reduced data from 0.6.131. 

Étienne could give more details, but at least, that would explain why new objects in `ccf_wrap.tbl` were not processed.

As of changing to a google sheets, that could be an interesting option as the API in Python is relatively simple.

**Comment by eartigau** [comment]
Yes, this became too messy with two flavours of the DRS around. @CharlesCadieux , if you could write a script to fetch a google spreadsheet that would have 5 columns: OBJECT MASK SANITIZED DRS_VERSION DONE, then I'll change (or you may also try it) my ccf_wrap to read that table and update it. I think that this is the best solution.

**Comment by CharlesCadieux** [comment]
Hi,

The integration of a ccf_wrap.tbl with Google Sheets is complete. I can discuss this at the next meeting. The Sheets is public at this link: 

https://docs.google.com/spreadsheets/d/1iNXrtNt8VRnuaPpfALBcCeF5rUh2vON57UO9Q75Xg_Q/edit#gid=0

I need to talk with Etienne to eventually update `ccf_wrap.py` on the master branch.
