### ISSUE TITLE
Results from analyse_TOI1452.py

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#3]
Please use the following Issue to add plots / add comments on results obtained by running:
`apero-utils/spirou/sandbox/ccf_tools/analyse_TOI1452.py`

Any problems please post in a new Issue to be solved quicker / closed when solved.

Note to add plots:

update to somewhere or put here: https://github.com/njcuk9999/apero-utils/tree/master/general/imagedump/

and use the following code to display them in an issue:
```
![alt text](http://url/to/img.png)
```

i.e.
```
![apero](https://raw.githubusercontent.com/njcuk9999/apero-utils/master/general/imagedump/apero_logo.png)
```

![apero](https://raw.githubusercontent.com/njcuk9999/apero-utils/master/general/imagedump/apero_logo.png)

Note for  analyse_TOI1278.py see Issue #2

**Comment by clairem789** [comment]
I was able to successfully run the analyse_TOI1452.py script as is, on Sep 25. 
Note that I had to create a TOI1452/ directory the first time in order to store the npy file, but that was the only thing I had to do. It would be more convenient that this file gets saved in the data directory (but I couldn't manage to do this change myself, yet).

Here's what I get :
We load TOI1452/TOI1452_sani_gl846_neg_ccf_cube.npy, this is speedier
We load values from headers, slower on first run, faster later
Order 23 has a CCF full of NaNs. Added to the rejected orders 
Order 37 has a CCF full of NaNs. Added to the rejected orders 
The CCF of order 17 has its minima -1.10 km/s from median CCF, above threshold of +-1.00 km/s


Template CCF iteration number   1, rms RV change 0.0213 km/s for this step
Template CCF iteration number   2, rms RV change 0.0007 km/s for this step
Template CCF iteration number   3, rms RV change 0.0001 km/s for this step
Template CCF iteration number   4, rms RV change 0.0001 km/s for this step
We load TOI1452/TOI1452_tcorr_gl846_neg_ccf_cube.npy, this is speedier
We load values from headers, slower on first run, faster later
Order 23 has a CCF full of NaNs. Added to the rejected orders 
Order 37 has a CCF full of NaNs. Added to the rejected orders 
The CCF of order 9 has its minima 1.60 km/s from median CCF, above threshold of +-1.00 km/s
The CCF of order 10 has its minima 3.90 km/s from median CCF, above threshold of +-1.00 km/s


Template CCF iteration number   1, rms RV change 0.0247 km/s for this step
Template CCF iteration number   2, rms RV change 0.0007 km/s for this step
Template CCF iteration number   3, rms RV change 0.0003 km/s for this step
Template CCF iteration number   4, rms RV change 0.0001 km/s for this step
Template CCF iteration number   5, rms RV change 0.0001 km/s for this step


For epoch MJD = 59004.51, the biggest outlier is at 1.156 median abs deviation
For epoch MJD = 59008.52, the biggest outlier is at 7.617 median abs deviation
For epoch MJD = 59030.48, the biggest outlier is at 4.475 median abs deviation
For epoch MJD = 59031.49, the biggest outlier is at 4.571 median abs deviation
For epoch MJD = 59032.45, the biggest outlier is at 2.634 median abs deviation
For epoch MJD = 59034.45, the biggest outlier is at 8.216 median abs deviation
For epoch MJD = 59035.43, the biggest outlier is at 4.829 median abs deviation
For epoch MJD = 59037.44, the biggest outlier is at 1.825 median abs deviation
For epoch MJD = 59038.45, the biggest outlier is at 2.280 median abs deviation
For epoch MJD = 59040.46, the biggest outlier is at 1.662 median abs deviation

This is the RV plot I got, but I'm not sure if those are the sanitized or tcorr data, as both are included.
 
![TOI1452_25sep](https://user-images.githubusercontent.com/32554392/94274227-b738ca00-ff45-11ea-8ee8-09a40e888b87.png)

Do you get exactly the same?

**Comment by eartigau** [comment]
this is a plot of the sanitized.  I updated the title. You can see from the code that we are using the tbl1, which is sanitized, but the title makes it clearer.

**Comment by edermartioli** [comment]
Here's my results for TOI-1452. Here I did two tests, first using all orders and then excluding orders "0,11,12,13,15,16,20,21,22,47,48".

The best configuration for this target are the following:

**When excluding orders:** GJ1214_neg.mas, Gl876_neg.mas, masque_sept18_andres_trans50.mas, all sanitized 
**Without order exclusion:** masque_sept18_andres_trans50.mas__sani  and Gl725B_neg.mas__tcorr

***
**YJHK no order exclusion**
***
TOI-1452__GJ1214_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=34.0 m/s mad=22.2 m/s
TOI-1452__Gl687_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=53.6 m/s mad=21.0 m/s
TOI-1452__Gl699_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=55.8 m/s mad=17.3 m/s
TOI-1452__Gl699_neg.mas__tcorr__0.6.131__YJHK__template.rdb: rms=23.0 m/s mad=30.1 m/s
TOI-1452__Gl725B_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=60.0 m/s mad=17.4 m/s
TOI-1452__Gl725B_neg.mas__tcorr__0.6.131__YJHK__template.rdb: rms=24.1 m/s mad=33.4 m/s
TOI-1452__Gl846_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=52.3 m/s mad=30.3 m/s
TOI-1452__Gl846_neg.mas__tcorr__0.6.131__YJHK__template.rdb: rms=26.7 m/s mad=26.2 m/s
TOI-1452__Gl876_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=45.7 m/s mad=19.2 m/s
TOI-1452__TOI-1452_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=113.9 m/s mad=47.6 m/s
TOI-1452__masque_sept18_andres_trans50.mas__sani__0.6.131__YJHK__template.rdb: rms=18.1 m/s mad=18.8 m/s
Median RVs: rms=26.1 m/s mad=20.1 m/s

![TOI-1452_YJHK_allorders](https://user-images.githubusercontent.com/23633657/94734355-7f63c500-033f-11eb-9be5-e76c7cac5c39.png)

***
**YJHK excluding orders "0,11,12,13,15,16,20,21,22,47,48"**
***
TOI-1452__GJ1214_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=19.2 m/s mad=15.4 m/s
TOI-1452__Gl687_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=20.4 m/s mad=19.8 m/s
TOI-1452__Gl699_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=18.0 m/s mad=20.5 m/s
TOI-1452__Gl699_neg.mas__tcorr__0.6.131__YJHK__template.rdb: rms=21.2 m/s mad=27.2 m/s
TOI-1452__Gl725B_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=18.2 m/s mad=17.9 m/s
TOI-1452__Gl725B_neg.mas__tcorr__0.6.131__YJHK__template.rdb: rms=24.1 m/s mad=29.2 m/s
TOI-1452__Gl846_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=21.6 m/s mad=18.4 m/s
TOI-1452__Gl846_neg.mas__tcorr__0.6.131__YJHK__template.rdb: rms=24.6 m/s mad=23.3 m/s
TOI-1452__Gl876_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=18.0 m/s mad=16.4 m/s
TOI-1452__TOI-1452_neg.mas__sani__0.6.131__YJHK__template.rdb: rms=91.4 m/s mad=25.8 m/s
TOI-1452__masque_sept18_andres_trans50.mas__sani__0.6.131__YJHK__template.rdb: rms=19.2 m/s mad=16.5 m/s
Median RVs: rms=18.3 m/s mad=18.0 m/s
![TOI-1452_YJHK_exclorders](https://user-images.githubusercontent.com/23633657/94735389-10876b80-0341-11eb-8c44-64dcf08b636a.png)

**Comment by eartigau** [comment]
Please check with the latest code that includes a projection of residuals against the 2nd derivative of the CCF. This is a direct measurement of the FWHM changes. You see the glitch at BJD ~32, which shows that this glitch is likely to be related to activity rather than a problem with the DRS.

**Comment by edermartioli** [comment]
In https://github.com/njcuk9999/apero-utils/issues/3#issuecomment-701625832 I have used the following commands:

```
python spirou_ccf_analysis.py --pattern=data/TOI-1452/*.fits
python rv_plots.py --pattern=data/TOI-1452/*.rdb --output=TOI-1452.rdb -c

python spirou_ccf_analysis.py --pattern=data/TOI-1452/*.fits --exclude_orders="0,11,12,13,15,16,20,21,22,47,48"
python rv_plots.py --pattern=data/TOI-1452/*.rdb --output=TOI-1452_excl_ords.rdb -c
```

Using the following wrapper that I wrote to run Etienne's codes:
https://github.com/edermartioli/spirou-ccf-analysis

**Comment by eartigau** [comment]
Do **not** use the masks constructed with the dat TOI targets themselves, they consistently give much worse results.

**Comment by eartigau** [comment]
could you add the spirou_ccf_analysis to GitHub ?

**Comment by eartigau** [comment]
Do you need to exclude all these ordres with the new 'bandpass' keywords ?

**Comment by vandalt** [comment]
Here is what I obtained with Étienne's script. With exclude_orders = [0,11,12,13,15,16,20,21,22,47,48], the two masks giving best results were Gl699 and Gl725B (based on mean per-epoch STDDEV).
![Screenshot-2020-10-01-11-24-06](https://user-images.githubusercontent.com/35547958/94829695-c5b93280-03d8-11eb-8982-131df9e5db7e.png)

**Comment by pfouque58** [comment]
Why do we use YJHK for this M4V target and HK only for TOI-1278 which is an M0V?

**Comment by eartigau** [comment]
I don't know. These are **sample** analysis codes, not a rigid framework. For TOI-1278, it's simply that HK does a marginally better job.
