### ISSUE TITLE
Wrapper for CCF tools

### ISSUE THREAD

**Issue by vandalt** [njcuk9999/apero-utils#7]
As discussed in meeting, we need to develop a wrapper for CCF tools developed by @eartigau. @edermartioli already has a wrapper script. We can update it to the newest version and keep it in this repo.

**Comment by vandalt** [comment]
@edermartioli Is the latest version of you script the one we can find here: https://github.com/edermartioli/spirou-ccf-analysis/

**Comment by edermartioli** [comment]
> @edermartioli Is the latest version of you script the one we can find here: https://github.com/edermartioli/spirou-ccf-analysis/ ?

@vandalt yes it's already the latest version.  Do you want to give it a try and implement it along with the latest version of Etienne's codes?  The wrapper itself is very simple, but it requires some modifications in the ccf2rv.py library.  Check my version of ccf2rv to get the functions that I included there to run the wrapper.   Since you will be working on the ccf2rv.py library, I think it would be very helpful if you could organize the code in get_object_rv(). This is a very long function, hard to maintain. There are some plotting stuff that could be done by another function and re-used several times.  Many other places in the code could use functions as well to avoid long codes.  Let me know if you will do it, otherwise, I can try to do it.

**Comment by edermartioli** [comment]
I agree with @njcuk9999  it's really important to work with branches and lock the master.

**Comment by vandalt** [comment]
I also agree, the only thing that we always need to edit in the master branch is the ccf_wrap.tbl because the ccf_wrap script reads it automatically from this location. @edermartioli I can work on updating your wrapper and the ccf2rv functions.

**Comment by njcuk9999** [comment]
So after talking to Etienne it may be better ccf_wrap.tbl as a google sheet (for example) and have his script have an interface with that ccf_wrap.tbl - to read and write to it and allow people to edit it (like I suggested for the data management google sheet) - github isn't really the place for data (just scripts).
Maybe @CharlesCadieux and/or @vandalt could have a good at this -- it would be a good test case for getting the data management google sheet working?

**Comment by edermartioli** [comment]
I asked @vandalt to implement the wrapper using the new version of the ccf2rv codes. But I've started to check things and since it wasn't so different than what I've done bofore I quickly implemented it already. So you may wanna check this new version rather than the old one as a starting point, if you haven't started yet (sorry!).  I've pushed it to my branch "eder" and I've also updated it in https://github.com/edermartioli/spirou-ccf-analysis . There's been so many changes in ccf2rv.py that it might be very difficult to "just" merge my branch modifications to the master.  I've re-organized the code completely, so there are many more functions in ccf2rv now. Just to give you a hint, get_object_rv() has only 170 lines compared to 621 lines before!  I've also found some "loose wires" which I've tried to fix.

**Comment by vandalt** [comment]
Great, thanks! I will use this as a starting point and will make a PR as soon as a new version compatible with the master branch is ready.

**Comment by eartigau** [comment]
Have you tried it side-by-side to confirm that the code gives the same outputs?
We should add some comments for each function and then set that file as the master as it will be clearer.

**Comment by edermartioli** [comment]
> Have you tried it side-by-side to confirm that the code gives the same outputs?
> We should add some comments for each function and then set that file as the master as it will be clearer.

Yes, I tested in some data sets (TOI-1278 and TOI-1452) and compared with the results using the respective analyse_TARGET.py . The results are compatible and even a bit better since we can easily run a batch of several types of reduction and compare the final RMS/MAD. 

You're right, now we need to work on the documentation of functions, and also on testing it on different data sets. I've already tested it on at least 5 other WP2 targets which are being analysed by Guillaume, and also on AU Mic transit, and the results are surprisingly compatible with the results that I presented in the paper.  There are some parts of the code which I think could be discussed and perhaps improved, but I think we should focus first on getting it in a more manageable format before we move to further improvements.

**Comment by eartigau** [comment]
@edermartioli with exactly the same inputs, do you get exactly the same outputs? I'm not surprised that you can improve as there are lots of degrees of freedom in there and we just started exploring... that's good news!

I agree, lets make it manageable. I won't work on it this week, so have fun!

**Comment by vandalt** [comment]
The wrapper is now available on the master branch. I will close the issue, but feel free to open a new ones if there are bugs/things missing in the scripts.
